name: build
on: push

jobs:
  build:
    strategy:
      matrix:
        include:
        - { target: win32 }
        - { target: win64 }
    runs-on: ubuntu-latest
    env:
      CFLAGS: '-Werror'
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y mingw-w64
    - run: make ${{ matrix.target }}

