name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CFLAGS: '-Werror -O2'
      LDFLAGS: '-s'
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y mingw-w64
    - run: make -j dist
    - uses: actions/upload-artifact@v4
      with:
        name: spoon
        path: dist/*.exe
