name: build
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      CFLAGS: '-Werror -O2'
      LDFLAGS: '-s'
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y bmake mingw-w64
    - run: bmake win32
    - run: bmake win64
    - uses: actions/upload-artifact@v4
      with:
        name: spoon
        path: bin/*

  msys:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      CFLAGS: '-Werror -O2'
      LDFLAGS: '-s'
    steps:
    - uses: actions/checkout@v4
    - run: pacman -S bmake
    - run: bmake msys
    - uses: actions/upload-artifact@v4
      with:
        name: spoon-msys
        path: bin/*
