name: build
on: push

jobs:
  ubuntu-mingw:
    runs-on: ubuntu-latest
    env:
      CFLAGS: '-Werror -O2'
      LDFLAGS: '-s'
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y mingw-w64
    - run: make -j dist
    - uses: actions/upload-artifact@v4
      with:
        name: spoon
        path: dist/*

  windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      CC: gcc
      CFLAGS: '-Werror -O2'
      LDFLAGS: '-s'
    steps:
    - uses: actions/checkout@v4
    - run: make -j default
    - uses: actions/upload-artifact@v4
      with:
        name: spoon-windows-mingw
        path: build/default/spoon.exe
