name: build
on: push

jobs:
  build:
    strategy:
      matrix:
        include:
        - { agent: ubuntu-latest, target: win32 }
        - { agent: ubuntu-latest, target: win64 }
        - { agent: debian12-agent, target: win32 }
        - { agent: debian12-agent, target: win64 }
    runs-on: '${{ matrix.agent }}'
    env:
      CFLAGS: '-Werror'
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y mingw-w64
    - run: make ${{ matrix.target }}

